after-login-command = []
after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

[gaps]
inner.horizontal = 20
inner.vertical =   20
outer.bottom =     20
outer.top =        20
outer.left =       20
outer.right =      20

[[on-window-detected]]
if.app-id = 'org.mozilla.com.zen.browser'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.jetbrains.datagrip'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 5'

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'secondary'
3 = 'secondary'
4 = 'secondary'
5 = 'secondary'


[mode.main.binding]
alt-shift-u = 'layout tiles horizontal'
alt-shift-i = 'layout accordion horizontal'
alt-shift-h = 'focus left'
alt-shift-l = 'focus right'
alt-shift-y = 'move left'
alt-shift-o = 'move right'
alt-shift-j = 'resize smart -50'
alt-shift-k = 'resize smart +50'

alt-shift-1 = 'workspace 1'
alt-shift-2 = 'workspace 2'
alt-shift-3 = 'workspace 3'
alt-shift-4 = 'workspace 4'
alt-shift-5 = 'workspace 5'
