return {
	-- "nvim-telescope/telescope-project.nvim",
	-- dependencies = {
	-- 	"nvim-telescope/telescope.nvim",
	-- 	"nvim-telescope/telescope-file-browser.nvim",
	-- },
	-- config = function()
	-- 	require("telescope").load_extension("project")
	-- 	local project_actions = require("telescope._extensions.project.actions")
	-- 	require('telescope').setup({
	-- 		extensions = {
	-- 			project = {
	-- 				base_dirs = {
	-- 					{ '~/dev',        max_depth = 8 },
	-- 				},
	-- 				hidden_files = true, -- default: false
	-- 				theme = "dropdown",
	-- 				order_by = "asc",
	-- 				search_by = "title",
	-- 				sync_with_nvim_tree = true, -- default false
	-- 				-- default for on_project_selected = find project files
	-- 				on_project_selected = function(prompt_bufnr)
	-- 					-- Do anything you want in here. For example:
	-- 					project_actions.change_working_directory(prompt_bufnr, false)
	-- 					require("harpoon.ui").nav_file(1)
	-- 				end
	-- 			}
	-- 		}
	-- 	})
	-- end,
}
